require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ChargesController do

  # This should return the minimal set of attributes required to create a valid
  # Charge. As you add validations to Charge, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ChargesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all charges as @charges" do
      charge = Charge.create! valid_attributes
      get :index, {}, valid_session
      assigns(:charges).should eq([charge])
    end
  end

  describe "GET show" do
    it "assigns the requested charge as @charge" do
      charge = Charge.create! valid_attributes
      get :show, {:id => charge.to_param}, valid_session
      assigns(:charge).should eq(charge)
    end
  end

  describe "GET new" do
    it "assigns a new charge as @charge" do
      get :new, {}, valid_session
      assigns(:charge).should be_a_new(Charge)
    end
  end

  describe "GET edit" do
    it "assigns the requested charge as @charge" do
      charge = Charge.create! valid_attributes
      get :edit, {:id => charge.to_param}, valid_session
      assigns(:charge).should eq(charge)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Charge" do
        expect {
          post :create, {:charge => valid_attributes}, valid_session
        }.to change(Charge, :count).by(1)
      end

      it "assigns a newly created charge as @charge" do
        post :create, {:charge => valid_attributes}, valid_session
        assigns(:charge).should be_a(Charge)
        assigns(:charge).should be_persisted
      end

      it "redirects to the created charge" do
        post :create, {:charge => valid_attributes}, valid_session
        response.should redirect_to(Charge.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved charge as @charge" do
        # Trigger the behavior that occurs when invalid params are submitted
        Charge.any_instance.stub(:save).and_return(false)
        post :create, {:charge => { "id" => "invalid value" }}, valid_session
        assigns(:charge).should be_a_new(Charge)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Charge.any_instance.stub(:save).and_return(false)
        post :create, {:charge => { "id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested charge" do
        charge = Charge.create! valid_attributes
        # Assuming there are no other charges in the database, this
        # specifies that the Charge created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Charge.any_instance.should_receive(:update).with({ "id" => "1" })
        put :update, {:id => charge.to_param, :charge => { "id" => "1" }}, valid_session
      end

      it "assigns the requested charge as @charge" do
        charge = Charge.create! valid_attributes
        put :update, {:id => charge.to_param, :charge => valid_attributes}, valid_session
        assigns(:charge).should eq(charge)
      end

      it "redirects to the charge" do
        charge = Charge.create! valid_attributes
        put :update, {:id => charge.to_param, :charge => valid_attributes}, valid_session
        response.should redirect_to(charge)
      end
    end

    describe "with invalid params" do
      it "assigns the charge as @charge" do
        charge = Charge.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Charge.any_instance.stub(:save).and_return(false)
        put :update, {:id => charge.to_param, :charge => { "id" => "invalid value" }}, valid_session
        assigns(:charge).should eq(charge)
      end

      it "re-renders the 'edit' template" do
        charge = Charge.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Charge.any_instance.stub(:save).and_return(false)
        put :update, {:id => charge.to_param, :charge => { "id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested charge" do
      charge = Charge.create! valid_attributes
      expect {
        delete :destroy, {:id => charge.to_param}, valid_session
      }.to change(Charge, :count).by(-1)
    end

    it "redirects to the charges list" do
      charge = Charge.create! valid_attributes
      delete :destroy, {:id => charge.to_param}, valid_session
      response.should redirect_to(charges_url)
    end
  end

end
